export const ORDER_STATUS = {
    COOKING: 'PREPARANDO ORDEN',
    READY: 'ORDEN LISTA',
    SERVED: 'ORDEN SERVIDA',
    DELIVERING: 'EN REPARTO',
    PICKUP_READY: 'ORDEN LISTA PARA PICKUP',
    PICKUP_COMPLETED: 'RECOGIDO POR CLIENTE',
    COMPLETED: 'FINALIZADA',
    CANCELLED: 'CANCELADO'
};
