export const ORDER_STATUS = {
    COOKING: 'PREPARANDO ORDEN',
    READY: 'ORDEN LISTA',
    SERVED: 'ORDEN SERVIDA',
    DELIVERING: 'EN REPARTO',
    COMPLETED: 'FINALIZADA',
    CANCELLED: 'CANCELADO'
};
